globals:
  vpc:
    cidr: "10.0.0.0/16"
    max_azs: 2
    subnet_mask: 24
    enable_dns_hostnames: true
    enable_dns_support: true
    nat_gateways: 0
  
  ec2:
    instance_type: "t3.micro"
    instance_class: "BURSTABLE2"
    instance_size: "MICRO"
    amazon_linux_edition: "STANDARD"
    virtualization: "HVM"
    storage: "GENERAL_PURPOSE"
  
  logging:
    flow_logs_group_name: "/aws/vpc/flowlogs"
    retention_days: 2
    
  endpoints:
    services:
      - name: "ssm"
        service: "SSM"
      - name: "ssm_messages"
        service: "SSM_MESSAGES"
      - name: "ec2_messages"
        service: "EC2_MESSAGES"
      - name: "ec2"
        service: "EC2"
      - name: "sts"
        service: "STS"
      - name: "logs"
        service: "CLOUDWATCH_LOGS"

accounts:
  - name: sandbox
    account: "${SANDBOX_ACCOUNT_ID}"    # Environment variable
    region: "${SANDBOX_REGION}"         # Environment variable
    vpc:
      cidr: "10.1.0.0/16"
    ec2:
      instance_type: "t3.micro"
  
  - name: production
    account: "${PRODUCTION_ACCOUNT_ID}"  # Environment variable
    region: "${PRODUCTION_REGION}"       # Environment variable
    vpc:
      cidr: "10.2.0.0/16"
      max_azs: 3
    ec2:
      instance_type: "t3.small"
      instance_class: "BURSTABLE2"
      instance_size: "SMALL"
    logging:
      retention_days: 30
      
  - name: development
    account: "${DEV_ACCOUNT_ID}"         # Environment variable
    region: "${DEV_REGION}"              # Environment variable
    vpc:
      cidr: "10.3.0.0/16"
    ec2:
      instance_type: "t3.nano"