globals:
  vpc:
    cidr: "10.0.0.0/16"
    max_azs: 2
    subnet_mask: 24
    enable_dns_hostnames: true
    enable_dns_support: true
    nat_gateways: 0
  
  ec2:
    instance_type: "t3.micro"
    instance_class: "BURSTABLE2"
    instance_size: "MICRO"
    amazon_linux_edition: "STANDARD"
    virtualization: "HVM"
    storage: "GENERAL_PURPOSE"
    key_name: "rinku-depot2"
    # Optional: specific AMI override
    ami_id: "ami-0e86e20dae9224db8"  # Ubuntu 24.04 us-east-1
  
  guacamole:
    instance_type: "t3.medium"
    instance_class: "BURSTABLE3"
    instance_size: "MEDIUM"
    ebs_volume_size: 10
    ebs_volume_type: "GP3"
    enable_monitoring: true
    ami_id: "ami-0e86e20dae9224db8"

  workstation:
    # Instance configuration
    instance_class: "BURSTABLE3"
    instance_size: "MEDIUM"
    architecture: "x86_64"  # or "arm64"
    # Storage configuration
    root_volume_size: 10  # GB
    root_volume_type: "GP3"
    # Guacamole configuration  
    guacamole_port: 8080
    vnc_port: 5901
    rdp_port: 3389
    # Domain configuration
    domain_pattern: "*.workstation.vadai.org"
    # Development tools
    install_vscode: true
    install_intellij: false
    install_docker: true  # Already in AMI
    
  cognito:  
    user_pool_name: GuacamolePool
    domain_prefix: guacamole-auth
    callback_urls:
      - https://guac.webdev.vadai.org/oauth2/idpresponse
    saml_provider_name: Zitadel
    saml_metadata_url: https://dev-ugeino.us1.zitadel.cloud/saml/v2/metadata
    attribute_mapping:
      email: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
      name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
  
  logging:
    flow_logs_group_name: "/aws/vpc/flowlogs"
    retention_days: 2

  waf:
    enabled: true
    name: "DdevWaf"
    description: "WAF for DDEV Demo Stack"
    cloudwatch_metrics_enabled: true
    sampled_requests_enabled: true
    blocked_countries:
      - "RU"  # Russia
      - "CN"  # China  
      - "KP"  # North Korea
      - "IR"  # Iran (optional)
    # IP Allow List (CIDR blocks)
    allowed_ips:
      ##- "0.0.0.0/0"
      - "73.194.145.1/32" ## bala home
      - "24.191.74.224/32" ## gov home
    allowed_fqdns:
      - "home.vadai.org"
    # AWS Managed Rules (boolean controls)
    aws_common_rule_set: true       # AWS Core Rule Set
    aws_known_bad_inputs: true      # Known Bad Inputs
    aws_sql_injection: true         # SQL Injection Protection
    aws_xss_protection: true        # XSS Protection
    aws_rate_limiting: false        # Rate limiting (can be expensive)
    rate_limit_requests: 500       # Requests per 5 minutes if rate limiting enabled
    
  endpoints:
    services:
      - name: "ssm"
        service: "SSM"
      - name: "ssm_messages"
        service: "SSM_MESSAGES"
      - name: "ec2_messages"
        service: "EC2_MESSAGES"
      - name: "ec2"
        service: "EC2"
      - name: "sts"
        service: "STS"
      - name: "logs"
        service: "CLOUDWATCH_LOGS"

accounts:
  - name: sandbox
    account: "${SANDBOX_ACCOUNT_ID}"    # Environment variable
    region: "${SANDBOX_REGION}"         # Environment variable
    vpc:
      cidr: "10.1.0.0/16"
    ec2:
      instance_type: "t3.micro"
  
  - name: production
    account: "${PRODUCTION_ACCOUNT_ID}"  # Environment variable
    region: "${PRODUCTION_REGION}"       # Environment variable
    vpc:
      cidr: "10.2.0.0/16"
      max_azs: 3
    ec2:
      instance_type: "t3.small"
      instance_class: "BURSTABLE2"
      instance_size: "SMALL"
    logging:
      retention_days: 30
      
  - name: development
    account: "${DEV_ACCOUNT_ID}"         # Environment variable
    region: "${DEV_REGION}"              # Environment variable
    vpc:
      cidr: "10.3.0.0/16"
    ec2:
      instance_type: "t3.nano"
